### ISSUE TITLE
[META] Binary type support with Faiss engine

### ISSUE THREAD

**Issue by heemin32** [opensearch-project/k-NN#1764]
There has been an increasing interest on binary format support from customers recently with many evidence showing good recall with binary value generated from LLM. As KNN with large data set is expensive due to cost of memory, customer want to use binary format instead of float format to reduce the required memory size by 1/32. 

### Tasks
High Level Tasks:
- [x] Create RFC for the Feature Request. https://github.com/opensearch-project/k-NN/issues/1767
- [ ] HNSW support
  - [x] JNI interface
  - [x] POC https://github.com/heemin32/k-NN/commit/efa0199bddd03e0fb9e31e796fcccb47e37105c0
  - [x] Faiss patch to support SearchParameter for binary index
  - [x] Index mapping, Ingestion, Query
  - [ ] Benchmark
- [x] Script scoring support on binary vector with hamming distance
  - [x] Block non hamming distance scoring on binary vector
  - [x] Implement script scoring with hamming distance on binary vector
- [x] IVF support
  - [x] JNI interface
  - [x] Faiss patch
  - [x] Training, Ingestion, Query
  - [ ] Benchmark
- [ ] Radial search
  - [ ] Radial search with HNSW
  - [ ] Radial search with IVF
  - [ ] Benchmark

### Community Requests
1. https://github.com/opensearch-project/k-NN/issues/81
