### ISSUE TITLE
[META]: Boosting Opensearch Vector Engine Performance using GPUs

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/k-NN#2295]
## Description
This is a meta to track the work required to complete the feature: Boosting Opensearch Vector Engine Performance using GPUs

### High Level Tasks
- [X] Benchmarks comparing perf of GPUs with CPUs, added as part of #2294. Benchmarks repo: https://github.com/navneet1v/VectorSearchForge
- [X] RFC with HLD for Boosting Opensearch Vector Engine Performance using GPUs (https://github.com/opensearch-project/k-NN/issues/2294)
- [X] RFC for Remote Vector Index Build Feature with OpenSearch Vector Engine (Ref: https://github.com/opensearch-project/k-NN/issues/2294)
- [ ] Complete a small POC

### Vector Index Build Component Tasks
- [ ] Detailed design for Vector Index Build Component
- [ ] Implementation

### Remote Vector Index Build Feature with OpenSearch Vector Engine
- [ ] Detailed design for Remote Vector Index Build Feature with OpenSearch Vector Engine
- [ ] Implementation
